line-length = 110
target-version = "py312"

[lint]
select = ["E", "F", "W", "I", "N", "UP", "B"]
ignore = []

[lint.per-file-ignores]
"tours/migrations/*" = ["E501", "I001", "N806"]
"chatbot/migrations/*" = ["E501", "I001", "N806"]

[format]
quote-style = "single"
