# Generated by Django 6.0.7 on 2026-07-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='sesión')),
                (
                    'role',
                    models.CharField(
                        choices=[('user', 'Usuario'), ('assistant', 'Asistente')],
                        max_length=10,
                        verbose_name='rol',
                    ),
                ),
                ('content', models.TextField(verbose_name='contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'mensaje de chat',
                'verbose_name_plural': 'mensajes de chat',
                'ordering': ['created_at'],
            },
        ),
    ]
