# Generated by Django 6.0.7 on 2026-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotPrompt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'content',
                    models.TextField(
                        help_text='Instrucciones que definen la personalidad y las reglas del asistente. Los cambios se aplican de inmediato, sin reiniciar el servidor.',
                        verbose_name='prompt del sistema',
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'prompt del chatbot',
                'verbose_name_plural': 'prompt del chatbot',
            },
        ),
    ]
