# Generated by Django 6.0.7 on 2026-07-18 16:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GastronomicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('image', models.ImageField(blank=True, upload_to='gastronomic_offers/', verbose_name='imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio')),
            ],
            options={
                'verbose_name': 'oferta gastronómica',
                'verbose_name_plural': 'ofertas gastronómicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('photo', models.ImageField(blank=True, upload_to='guides/', verbose_name='foto')),
                ('age', models.PositiveIntegerField(verbose_name='edad')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='sexo')),
            ],
            options={
                'verbose_name': 'guía',
                'verbose_name_plural': 'guías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio adultos')),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio niños (hasta 12 años)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='tours.category', verbose_name='categoría')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='tours.location', verbose_name='lugar de destino')),
            ],
            options={
                'verbose_name': 'excursión',
                'verbose_name_plural': 'excursiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='excursions/photos/', verbose_name='imagen')),
                ('photo_type', models.CharField(choices=[('destination', 'Destino'), ('transport', 'Transporte')], default='destination', max_length=20, verbose_name='tipo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.excursion', verbose_name='excursión')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['photo_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, upload_to='excursions/videos/', verbose_name='archivo de video')),
                ('video_url', models.URLField(blank=True, help_text='Alternativa al archivo: enlace de YouTube u otro.', verbose_name='URL del video')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tours.excursion', verbose_name='excursión')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='OptionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_activities', to='tours.excursion', verbose_name='excursión')),
            ],
            options={
                'verbose_name': 'actividad opcional',
                'verbose_name_plural': 'actividades opcionales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('image', models.ImageField(blank=True, upload_to='pickup_points/', verbose_name='imagen')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_points', to='tours.location', verbose_name='localidad')),
            ],
            options={
                'verbose_name': 'punto de recogida',
                'verbose_name_plural': 'puntos de recogida',
                'ordering': ['location__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacidad')),
                ('payment_address', models.CharField(max_length=255, verbose_name='dirección de pago')),
                ('contact_phone', models.CharField(help_text='Con código de país, ej. +5352123456. Se usa para el chat de WhatsApp.', max_length=20, verbose_name='teléfono de contacto')),
                ('departure_time', models.TimeField(verbose_name='hora de salida')),
                ('return_time', models.TimeField(verbose_name='hora de retorno')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tours.excursion', verbose_name='excursión')),
                ('gastronomic_offers', models.ManyToManyField(blank=True, related_name='slots', to='tours.gastronomicoffer', verbose_name='ofertas gastronómicas')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='tours.guide', verbose_name='guía')),
                ('pickup_point', models.ForeignKey(blank=True, help_text='Se define luego de tener todas las capacidades vendidas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='tours.pickuppoint', verbose_name='punto de recogida')),
            ],
            options={
                'verbose_name': 'salida (slot)',
                'verbose_name_plural': 'salidas (slots)',
                'ordering': ['date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad de adultos')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='cantidad de niños (hasta 12 años)')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('representative_name', models.CharField(max_length=150, verbose_name='nombre del representante')),
                ('representative_phone', models.CharField(max_length=20, verbose_name='teléfono del representante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tours.slot', verbose_name='salida')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('excursion', 'date', 'departure_time'), name='unique_slot_departure'),
        ),
    ]
