# Generated by Django 6.0.7 on 2026-07-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_seed_locations_and_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('x', 'X')], max_length=20, unique=True, verbose_name='plataforma')),
                ('url', models.URLField(help_text='URL del perfil, ej. https://instagram.com/mastour', verbose_name='enlace')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'red social',
                'verbose_name_plural': 'redes sociales',
                'ordering': ['platform'],
            },
        ),
    ]
