# Generated by Django 6.0.7 on 2026-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('role', models.CharField(max_length=150, verbose_name='cargo')),
                ('quote', models.CharField(blank=True, help_text='Frase personal mostrada en cursiva.', max_length=200, verbose_name='frase')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'miembro del equipo',
                'verbose_name_plural': 'miembros del equipo',
                'ordering': ['order', 'id'],
            },
        ),
    ]
