# Generated by Django 6.0.7 on 2026-07-18 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada')], default='pending', help_text='Pasa a "Completada" automáticamente cuando vence la hora de retorno (hora de La Habana).', max_length=20, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('slot', models.OneToOneField(help_text='Solo se puede asociar a salidas completadas.', limit_choices_to={'status': 'completed'}, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='tours.slot', verbose_name='salida')),
            ],
            options={
                'verbose_name': 'recuerdo',
                'verbose_name_plural': 'recuerdos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memories/', verbose_name='imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.memory', verbose_name='recuerdo')),
            ],
            options={
                'verbose_name': 'imagen del recuerdo',
                'verbose_name_plural': 'imágenes del recuerdo',
                'ordering': ['id'],
            },
        ),
    ]
