# Generated by Django 6.0.7 on 2026-07-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_slot_status_memory_memoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='pregunta')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ['order', 'id'],
            },
        ),
    ]
