# Generated by Django 6.0.7 on 2026-07-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('x', 'X'), ('telegram', 'Telegram')], max_length=20, unique=True, verbose_name='plataforma'),
        ),
    ]
