# Generated by Django 6.0.7 on 2026-07-20 20:56

from django.db import migrations, models


def migrate_activities_to_catalog(apps, schema_editor):
    """Copy each activity's excursion into the new M2M and merge duplicate names."""
    OptionalActivity = apps.get_model('tours', 'OptionalActivity')

    # 1. Preserve existing links: FK excursion -> M2M optional_activities.
    for activity in OptionalActivity.objects.all():
        if activity.excursion_id:
            activity.excursions.add(activity.excursion_id)

    # 2. Deduplicate by name so the catalog can enforce unique names,
    #    moving every excursion of a duplicate onto the first activity kept.
    seen = {}
    for activity in OptionalActivity.objects.order_by('id'):
        key = activity.name.strip().lower()
        canonical = seen.get(key)
        if canonical is None:
            seen[key] = activity
            continue
        for excursion_id in activity.excursions.values_list('id', flat=True):
            canonical.excursions.add(excursion_id)
        activity.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_sociallink_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='title',
        ),
        migrations.AddField(
            model_name='excursion',
            name='optional_activities',
            field=models.ManyToManyField(blank=True, related_name='excursions', to='tours.optionalactivity', verbose_name='actividades opcionales'),
        ),
        migrations.RunPython(migrate_activities_to_catalog, noop),
        migrations.RemoveField(
            model_name='optionalactivity',
            name='excursion',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='optionalactivity',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='nombre'),
        ),
    ]
